### ISSUE TITLE
6700xt fails to initialize

### ISSUE THREAD

**Issue by rsparkyc** [todxx/teamredminer#251]
Have a 5700xt and a 6700xt installed, getting the following error when starting the miner:

```
teamredminer.exe -a ethash -o stratum+tcp://us1.ethermine.org:4444 -u 0x....... -p x
          Team Red Miner version 0.8.1
[2021-03-18 11:50:49] Pool us1.ethermine.org: Ethermine ethash auto mode detected, setting --eth_stratum=ethproxy
[2021-03-18 11:50:49] Auto-detected AMD OpenCL platform 0
[2021-03-18 11:50:49] Auto-detected AMD OpenCL platform 1
[2021-03-18 11:50:52] Excluding OpenCL device idx 0 on selected platform 1, duplicate device.
[2021-03-18 11:50:52] Excluding OpenCL device idx 1 on selected platform 1, duplicate device.
[2021-03-18 11:50:53] Initialize error, unknown device name: 'gfx1031'
[2021-03-18 11:50:53] Failed to initialize device idx 0 (-9)
[2021-03-18 11:50:53] Successful clean shutdown.
```

**Comment by rsparkyc** [comment]
list_devices shows this:

```
teamredminer.exe --list_devices
          Team Red Miner version 0.8.1
[2021-03-18 11:55:43] Auto-detected AMD OpenCL platform 0
[2021-03-18 11:55:43] Auto-detected AMD OpenCL platform 1
[2021-03-18 11:55:46] Excluding OpenCL device idx 0 on selected platform 1, duplicate device.
[2021-03-18 11:55:46] Excluding OpenCL device idx 1 on selected platform 1, duplicate device.
[2021-03-18 11:55:46] Detected 2 devices, listed in pcie bus id order:
[2021-03-18 11:55:46] Miner Platform OpenCL BusId    Name          Model                     Nr CUs
[2021-03-18 11:55:46] ----- -------- ------ -------- ------------- ------------------------- ------
[2021-03-18 11:55:46]     0        0      0 03:00.0  gfx1031       AMD Radeon RX 6700 XT         20
[2021-03-18 11:55:46]     1        0      1 07:00.0  gfx1010       AMD Radeon RX 5700 XT         20
[2021-03-18 11:55:46] Successful clean shutdown.
```

**Comment by pdieppa** [comment]
What version of OpenCL are you running?

**Comment by rsparkyc** [comment]
I ran clinfo and got this: (FWIW, I ran this when I just had 2 5700 XTs in, since they mine faster, and I don't have my risers yet to have those and the 6700 XT installed) 

```
Number of platforms:                             2
  Platform Profile:                              FULL_PROFILE
  Platform Version:                              OpenCL 2.1 AMD-APP (3224.5)
  Platform Name:                                 AMD Accelerated Parallel Processing
  Platform Vendor:                               Advanced Micro Devices, Inc.
  Platform Extensions:                           cl_khr_icd cl_khr_d3d10_sharing cl_khr_d3d11_sharing cl_khr_dx9_media_sharing cl_amd_event_callback cl_amd_offline_devices
  Platform Profile:                              FULL_PROFILE
  Platform Version:                              OpenCL 2.1 AMD-APP (3188.4)
  Platform Name:                                 AMD Accelerated Parallel Processing
  Platform Vendor:                               Advanced Micro Devices, Inc.
  Platform Extensions:                           cl_khr_icd cl_khr_d3d10_sharing cl_khr_d3d11_sharing cl_khr_dx9_media_sharing cl_amd_event_callback cl_amd_offline_devices
```

**Comment by shirixae** [comment]
Same error, OpenCL version 2.1, on second pc with 6800+6800XT openCL version is 2.0 and all works fine.

**Comment by rsparkyc** [comment]
Hmm, so maybe I should downgrade to 2.0?

**Comment by shirixae** [comment]
> Hmm, so maybe I should downgrade to 2.0?

I don't think so. If you disable 6700XT from device manager, your 5700XT will work wine on OpenCL 2.1 and will mine on the same hashrate as on OpenCL 2.0. Problem is not with OpenCL version. It's combo of OpenCL 2.1 + new GPU.

**Comment by rsparkyc** [comment]
Ok, but how does disabling the 6700XT from device manager allow me to mine on it? I'm getting risers in the mail so my plan is to mine on two 5700XTs and one 6700XT.

**Comment by rsparkyc** [comment]
any update on how to actually get this to work? I got my PCIE risers, and now have all my cards installed, but it still says "unknown device name: 'gfx1031'. 

@shirixae you said that your 6800XT works with OpenCL 2.1, does it show an device name of 'gfx1031'? That error makes me think that this app is looking for specific devices name, and since the 6700XT just came out, it's not updated to work with it. Perhaps I'm wrong.

**Comment by saintnx** [comment]
bump on this I'm having the exact same issue!

I'm trying to run an RX570 alongside my new RX6700XT (I'm on windows 10):

`teamredminer.exe --list_devices
          Team Red Miner version 0.8.1
[2021-03-21 05:10:34] Auto-detected AMD OpenCL platform 0
[2021-03-21 05:10:35] Detected 2 devices, listed in pcie bus id order:
[2021-03-21 05:10:35] Miner Platform OpenCL BusId    Name          Model                     Nr CUs
[2021-03-21 05:10:35] ----- -------- ------ -------- ------------- ------------------------- ------
[2021-03-21 05:10:35]     0        0      0 04:00.0  Ellesmere     Radeon RX 570 Series          32
[2021-03-21 05:10:35]     1        0      1 12:00.0  gfx1031       AMD Radeon RX 6700 XT         20
[2021-03-21 05:10:35] Successful clean shutdown.`

I can run the RX570 find by defining the device like so:
`teamredminer.exe --enable_compute -d 0 -a ethash -o stratum+tcp://eth.2miners.com:2020 -u 0x6A... -p x`

here's what I get when I try the RX6700XT:
`teamredminer.exe --enable_compute -d 1 -a ethash -o stratum+tcp://eth.2miners.com:2020 -u 0x6A...._trmtest_RX6700XT -p x
          Team Red Miner version 0.8.1
[2021-03-21 05:16:37] Running in administrator mode.
[2021-03-21 05:16:37] Auto-detected AMD OpenCL platform 0
[2021-03-21 05:16:38] Initialize error, unknown device name: 'gfx1031'
[2021-03-21 05:16:38] Failed to initialize device idx 1 (-9)
[2021-03-21 05:16:38] Successful clean shutdown.`

and here's what I get with clinfo:
`clinfo
Number of platforms:                             1
  Platform Profile:                              FULL_PROFILE
  Platform Version:                              OpenCL 2.1 AMD-APP (3224.5)
  Platform Name:                                 AMD Accelerated Parallel Processing
  Platform Vendor:                               Advanced Micro Devices, Inc.
  Platform Extensions:                           cl_khr_icd cl_khr_d3d10_sharing cl_khr_d3d11_sharing cl_khr_dx9_media_sharing cl_amd_event_callback cl_amd_offline_devices`


Any help is greatly appreciated!

**Comment by saintnx** [comment]
the only miner I was able to get to work with my RX6700XT is PhoenixMiner 

I tested lolminer and teamredminer which both gave similar issues :(((

**Comment by rsparkyc** [comment]
currently I'm using good old classic ethminer for my 6700XT, and letting teamredminer for the 5700XTs. @saintnx does PhoenixMiner have support for the Big Eth hash? I was curious how much boost that would give since the 6700XT has 12 gigs, or if it would still just be limited by the smaller memory bus width.

**Comment by saintnx** [comment]
@rsparkyc afk atm I'll investigate and report back, probably tomorrow

**Comment by saintnx** [comment]
slammed today hopefully I can investigate tomorrow or later this week :/

**Comment by rsparkyc** [comment]
@saintnx no worries, I know what that's like

**Comment by egarci21** [comment]
Until TRM fixes the issues you can use Gminer 2.47 or Phoenix miner 5.5c. Currently I'm using Gminer until the fix is in place.

**Comment by rsparkyc** [comment]
@egarci21 good to know, I talked with @Kerney666 and I think a test build might be in the works, so hopefully there will be support for it soon.

**Comment by rsparkyc** [comment]
Fixed with latest version

**Comment by kwilkins-82** [comment]
Still not working for me, on Ubuntu 20.04 with ROCM and the latest release of teamredminer - I get "Failed to initialize device idx 0 (-13)".   

Other miners are working OK, e.g. nanominer (though it reports hashrate incorrectly).

**Comment by Agamenox** [comment]
same fail Failed to initialize device idx 0 (-13)
![image](https://user-images.githubusercontent.com/8619960/128115040-72533f8e-9f9a-410a-8fc6-6bff6960c89e.png)
